#include<iostream>
using namespace std;
int main()
{
int Number1;
int Number2;
int Number3;
int Number4;
int Number5;
int Number6;
int Number7;
int Number8;
int Number9;
int Number10;
int Number11;
int Number12;
int Number13;
int Number14;
int Number15;
int add;
int mul;
int sub;
int Add2Numbers;
int result;
cout<<"Enter 1st Number :" ;
cin>>Number1;
cout<<"Enter 2nd Number :";
cin>>Number2;
cout<<"Enter 3rd Number :";
cin>>Number3;
cout<<"Enter 4th Number :";
cin>>Number4;
cout<<"Enter 5th Number :";
cin>>Number5 ;
cout<<"Enter 6th Number :";
cin>>Number6;
cout<<"Enter 7th Number :";
cin>>Number7;
cout<<"Enter 8th Number :";
cin>>Number8;
cout<<"Enter 9th Number :";
cin>>Number9;
cout<<"Enter 10th Number :";
cin>>Number10;
cout<<"Enter 11th Number :";
cin>>Number11;
cout<<"Enter 12th Number :";
cin>>Number12;
cout<<"Enter 13th Number :";
cin>>Number13;
cout<<"Enter 14th Number :";
cin>>Number14;
cout<<"Enter 15th number :";
cin>>Number15;
add=(Number1 + Number2 + Number3 + Number4 + Number5);
mul=(Number6 * Number7 * Number8 * Number9 *Number10);
sub=(Number11 - Number12 - Number13 - Number14 - Number15);
Add2Numbers=add + mul;
result=Add2Numbers - sub;
cout<<"Result is " <<result;
return 0;
}
